language: generic
sudo: required
services: 
  - docker
  
before_install:
  - docker build -t mvinicius890/docker-react -f Dockerfile.dev .
 
script:
  - docker run -e CI=true mvinicius890/docker-react npm run test
